### PR TITLE
Issue #35: string-push-back-reader read (e.g. files)

### PR DESCRIPTION
**Pull request by asheldo**
Fixed per the last comments in Issue #35 Working "open in" functionality. Switched read-eval-print to use kanaka's (r/read string-push-back-reader) and removed the wrapping "(do)" in AppDelegate call.

### CODE REVIEW

**Comment by mfikes** [comment]
Thanks! Awesome!

**Comment by mars0i** [comment]
Hi, Is this available yet in the distribution  version?  How can I use it?  I'm not sure I fully understand, but I tried to find Replete as an open-in option in other apps, and it's not there.  I may be being clueless, however.

Thank you for Replete.

(In an ideal world, it would be very nice if one could `require` at least the standard Clojure(script) libs from the repl, and have them automatically downloaded if necessary, but that's a kind of flexibility that would go well beyond the leiningen/boot paradigm for lib availability.)

**Comment by mfikes** [comment]
@mars0i If you have Lisping installed, files edited in that app can be opened in Replete. I believe this functionality works with other apps that can edit content and present Open In... menus, but I'm not familiar with any.

In terms of libraries, Replete ships with the bootstrapped ports of `test.check` and `core.async`.

But, being able to automatically download source for execution can cause an issue with the ability to ship Replete in the App Store. (For example [this feature](http://blog.fikesfarm.com/posts/2015-08-11-loading-clojurescript-into-your-iphone.html) had to be removed.)

**Comment by mars0i** [comment]
Ah, I figured out how to get the editor I have, Buffer, to do Open In.  Sorry about that.  (Lisping is intriguing--might get it.)  

I've been avoiding learning how to install a custom build, but I should do that--then subsequent custom builds for this or that (e.g. learning monads) will be easy.  Thanks.

**Pull request merged**
