### PR TITLE
#26 Allow reader conditionals for cljs

### PR DESCRIPTION
**Pull request by karlmikko**
screen shot 2015-07-08 at 12 43 51 pm

### CODE REVIEW

**Comment by mfikes** [comment]
Thanks! Awesome!

**Comment by karlmikko** [comment]
It worked in my tests first without it - I added it due to https://github.com/fogus/himera/pull/33

I think lets drop it and add it back in if needed.

**Comment by mfikes** [comment]
Yeah, it actually works for me, they are effectively just compiler warnings—nothing is breaking as far as I can tell. If you'd like to patch it to remove them, feel free. Otherwise, let me know and I can take care of it. Either way is cool.

**Comment by karlmikko** [comment]
I will do it now! :)

**Comment by karlmikko** [comment]
see #45

**Pull request merged**
